spring.application.name=calorie-tracker-api

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
